// packages/pdf-viewer-react/lib/PDFTree.jsx
import { useState } from "react"

export default function PDFTree({
  treeData = [],
  nodeKey = 'key',
  level = 0,
  onNodeClick,
  style
}) {
  const [expandKeys, setExpandKeys] = useState([]);
  function expandNode(node) {
    const key = node[nodeKey];
    const index = expandKeys.indexOf(key);
    if (index === -1) {
      setExpandKeys([...expandKeys, key])
    } else {
      setExpandKeys([...expandKeys.slice(0, index), ...expandKeys.slice(index + 1)])
    }
  }
  function clickHandler(e, node) {
    onNodeClick(node);
    e.stopPropagation();
  }
  return (
    <div 
      className="pdf-tree-wrapper"
      style={style}
    > 
      <ul>
        {
          treeData.map(node => {
            return <li
              key={node[nodeKey]}
              className="pdf-tree-item"
            >
              <div 
                className="pdf-tree-item-main"
                onClick={(e) => clickHandler(e, node)}  
              >
                {
                  Boolean(node.items.length) 
                  && <i 
                    className="icon iconfont icon-expand pdf-item-icon" 
                    style={{ transform: `rotate(${expandKeys.includes(node[nodeKey]) ? '0deg' : '-90deg'})` }}
                    onClick={() => expandNode(node)}
                  ></i>
                }
                <span className="pdf-item-text" title={node.title}>{ node.title }</span>
              </div>
              { 
                Boolean(node.items?.length) 
                && expandKeys.includes(node[nodeKey]) 
                &&  <PDFTree
                  treeData={node.items}
                  nodeKey={nodeKey}
                  level={level + 1}
                  onNodeClick={(_node) => onNodeClick(_node)}
                ></PDFTree>
              }
            </li>
          })
        }
      </ul>
    </div>
  )
}

// packages/pdf-viewer-vue2/lib/PDFTree.vue
<template>
  <div 
    class="w-full h-full overflow-auto"
  > 
    <ul>
      <li
        v-for="node in treeData"
        :key="node[nodeKey]"
        class="pl-[6px] overflow-hidden text-[--pdf-catalogue-text-color]"
      >
        <div 
          class="flex h-[20px] text-[12px] cursor-pointer hover:text-[--pdf-catalogue-text-highlight] leading-[20px] text-left mb-[6px]"
          @click.stop="toDest(node)"  
        >
          <i 
            v-if="node.items?.length"
            class="icon iconfont icon-expand text-[12px] transition-all" 
            :style="{ transform: `rotate(${expandKeys.includes(node[nodeKey]) ? '0deg' : '-90deg'})` }"
            @click.stop="expandNode(node)"
          ></i>
          <span class="ml-[3px] inline-block whitespace-nowrap overflow-hidden text-ellipsis" :title="node.title">{{ node.title }}</span>
        </div>
        <pdf-tree
          v-if="node.items?.length && expandKeys.includes(node[nodeKey])"
          :tree-data="node.items"
          :node-key="nodeKey"
          :level="level + 1"
          @node-click="(_node) => toDest(_node)"
        ></pdf-tree>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'pdf-tree',
  props: {
    treeData: {
      type: Array,
      default: () => []
    },
    nodeKey: {
      type: String,
      default: "key"
    },
    level: {
      type: Number,
      default: 0
    }
  },
  data() {
    return {
      expandKeys: []
    }
  },
  methods: {
    expandNode(node) {
      const key = node[this.nodeKey];
      const index = this.expandKeys.indexOf(key);
      if (index === -1) {
        this.expandKeys.push(key)
      } else {
        this.expandKeys.splice(index, 1)
      }
    },
    toDest(node) {
      this.$emit('node-click', node)
    }
  }
}
</script>
<style>

</style>
