// packages/pdf-viewer-vue3/lib/PDFTree.vue
<template>
  <div 
    class="pdf-tree-wrapper"
  > 
    <ul>
      <li
        v-for="node in treeData"
        :key="node[nodeKey]"
        class="pdf-tree-item"
      >
        <div 
          class="pdf-tree-item-main"
          @click.stop="$emit('nodeClick', node)"  
        >
          <i 
            v-if="node.items?.length"
            class="icon iconfont icon-expand pdf-item-icon" 
            :style="{ transform: `rotate(${expandKeys.includes(node[nodeKey]) ? '0deg' : '-90deg'})` }"
            @click.stop="expandNode(node)"
          ></i>
          <span class="pdf-item-text" :title="node.title">{{ node.title }}</span>
        </div>
        <PDFTree
          v-if="node.items?.length && expandKeys.includes(node[nodeKey])"
          :tree-data="node.items"
          :node-key="nodeKey"
          :level="level + 1"
          @node-click="(_node) => $emit('nodeClick', _node)"
        ></PDFTree>
      </li>
    </ul>
  </div>
</template>

<script>
import { defineComponent } from 'vue';

defineComponent({
  name: 'pdf-tree',
});
</script>

<script setup>
import { defineProps, defineEmits, ref } from 'vue';
const props = defineProps({
  treeData: {
    type: Array,
    default: () => []
  },
  nodeKey: {
    type: String,
    default: "key"
  },
  level: {
    type: Number,
    default: 0
  }
});
defineEmits(["nodeClick"]);
const expandKeys = ref([]);
function expandNode(node) {
  const key = node[props.nodeKey];
  const index = expandKeys.value.indexOf(key);
  if (index === -1) {
    expandKeys.value.push(key)
  } else {
    expandKeys.value.splice(index, 1)
  }
}
</script>

<style>

</style>

// packages/pdf-viewer-react/lib/PDFTree.jsx
import { useState } from "react"

export default function PDFTree({
  treeData = [],
  nodeKey = 'key',
  level = 0,
  onNodeClick,
  style
}) {
  const [expandKeys, setExpandKeys] = useState([]);
  function expandNode(node) {
    const key = node[nodeKey];
    const index = expandKeys.indexOf(key);
    if (index === -1) {
      setExpandKeys([...expandKeys, key])
    } else {
      setExpandKeys([...expandKeys.slice(0, index), ...expandKeys.slice(index + 1)])
    }
  }
  function clickHandler(e, node) {
    onNodeClick(node);
    e.stopPropagation();
  }
  return (
    <div 
      className="pdf-tree-wrapper"
      style={style}
    > 
      <ul>
        {
          treeData.map(node => {
            return <li
              key={node[nodeKey]}
              className="pdf-tree-item"
            >
              <div 
                className="pdf-tree-item-main"
                onClick={(e) => clickHandler(e, node)}  
              >
                {
                  Boolean(node.items.length) 
                  && <i 
                    className="icon iconfont icon-expand pdf-item-icon" 
                    style={{ transform: `rotate(${expandKeys.includes(node[nodeKey]) ? '0deg' : '-90deg'})` }}
                    onClick={() => expandNode(node)}
                  ></i>
                }
                <span className="pdf-item-text" title={node.title}>{ node.title }</span>
              </div>
              { 
                Boolean(node.items?.length) 
                && expandKeys.includes(node[nodeKey]) 
                &&  <PDFTree
                  treeData={node.items}
                  nodeKey={nodeKey}
                  level={level + 1}
                  onNodeClick={(_node) => onNodeClick(_node)}
                ></PDFTree>
              }
            </li>
          })
        }
      </ul>
    </div>
  )
}
